import { Menu } from 'antd';
import './index.scss';
import {
  AliyunOutlined,
  AppstoreAddOutlined,
  BgColorsOutlined,
  BuildOutlined,
  CalculatorOutlined,
  CodeSandboxOutlined,
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import {
  CentosIcon,
  FigmaIcon,
  JenkinsIcon,
  ListIcon,
  ModaoIcon,
  MozillaIcon,
  NginxIcon,
  NodejsIcon,
  SASSIcon,
  SSLIcon,
  TencentCloudIcon,
  TypeScriptIcon,
  VsCodeIcon,
  VueIcon,
} from '../../assets/icons';

function getItem(
  label?: any,
  key?: any,
  icon?: any,
  children?: any,
  type?: any
) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}

const items = [
  getItem('组件列表', 'components', <BuildOutlined />, [
    getItem('分割线 Divider', 'divider'),
    getItem('按钮 Button', 'button'),
  ]),
  getItem('算法实现', 'algorithms', <CalculatorOutlined />, [
    getItem('Lodash', 'lodash', null, [
      getItem('_./internal', 'internal', null, [
        getItem('Hash', 'Hash'),
        getItem('ListCache', 'ListCache'),
        getItem('MapCache', 'MapCache'),
        getItem('SetCache', 'SetCache'),
        getItem('Stack', 'Stack'),
        getItem('addMapEntry', 'addMapEntry'),
        getItem('addSetEntry', 'addSetEntry'),
        getItem('arrayEach', 'arrayEach'),
        getItem('arrayEachRight', 'arrayEachRight'),
        getItem('arrayIncludes', 'arrayIncludes'),
        getItem('arrayIncludesWith', 'arrayIncludesWith'),
        getItem('arrayLikeKeys', 'arrayLikeKeys'),
        getItem('arrayReduce', 'arrayReduce'),
        getItem('arrayReduceRight', 'arrayReduceRight'),
        getItem('asciiSize', 'asciiSize'),
        getItem('asciiToArray', 'asciiToArray'),
        getItem('assignMergeValue', 'assignMergeValue'),
        getItem('assignValue', 'assignValue'),
        getItem('assocIndexOf', 'assocIndexOf'),
        getItem('baseAssignValue', 'baseAssignValue'),
        getItem('baseAt', 'baseAt'),
        getItem('baseClone', 'baseClone'),
        getItem('baseConforms', 'baseConforms'),
        getItem('baseConformsTo', 'baseConformsTo'),
        getItem('baseDifference', 'baseDifference'),
        getItem('baseEach', 'baseEach'),
        getItem('baseEachRight', 'baseEachRight'),
        getItem('baseFindIndex', 'baseFindIndex'),
        getItem('baseFindKey', 'baseFindKey'),
        getItem('baseFlatten', 'baseFlatten'),
        getItem('baseFor', 'baseFor'),
        getItem('baseForOwn', 'baseForOwn'),
        getItem('baseForOwnRight', 'baseForOwnRight'),
        getItem('baseForRight', 'baseForRight'),
        getItem('baseGet', 'baseGet'),
        getItem('baseInRange', 'baseInRange'),
        getItem('baseIndexOf', 'baseIndexOf'),
        getItem('baseIndexOfWith', 'baseIndexOfWith'),
        getItem('baseIntersection', 'baseIntersection'),
        getItem('baseIsEqual', 'baseIsEqual'),
        getItem('baseIsEqualDeep', 'baseIsEqualDeep'),
        getItem('baseIsMatch', 'baseIsMatch'),
        getItem('baseIsNaN', 'baseIsNaN'),
        getItem('baseMatches', 'baseMatches'),
        getItem('baseMatchesProperty', 'baseMatchesProperty'),
        getItem('baseMerge', 'baseMerge'),
        getItem('baseMergeDeep', 'baseMergeDeep'),
        getItem('baseOrderBy', 'baseOrderBy'),
        getItem('basePick', 'basePick'),
        getItem('basePickBy', 'basePickBy'),
        getItem('baseProperty', 'baseProperty'),
        getItem('basePropertyDeep', 'basePropertyDeep'),
        getItem('basePropertyOf', 'basePropertyOf'),
        getItem('basePullAll', 'basePullAll'),
        getItem('basePullAt', 'basePullAt'),
        getItem('baseRange', 'baseRange'),
        getItem('baseReduce', 'baseReduce'),
        getItem('baseSet', 'baseSet'),
        getItem('baseSortBy', 'baseSortBy'),
        getItem('baseSortedIndex', 'baseSortedIndex'),
        getItem('baseSortedIndexBy', 'baseSortedIndexBy'),
        getItem('baseSortedUniq', 'baseSortedUniq'),
        getItem('baseSum', 'baseSum'),
        getItem('baseToNumber', 'baseToNumber'),
        getItem('baseToString', 'baseToString'),
        getItem('baseUniq', 'baseUniq'),
        getItem('baseUnset', 'baseUnset'),
        getItem('baseUpdate', 'baseUpdate'),
        getItem('baseValues', 'baseValues'),
        getItem('baseWhile', 'baseWhile'),
        getItem('baseXor', 'baseXor'),
        getItem('baseZipObject', 'baseZipObject'),
        getItem('cacheHas', 'cacheHas'),
        getItem('castArrayLikeObject', 'castArrayLikeObject'),
        getItem('castPath', 'castPath'),
        getItem('castSlice', 'castSlice'),
        getItem('charsEndIndex', 'charsEndIndex'),
        getItem('charsStartIndex', 'charsStartIndex'),
        getItem('cloneArrayBuffer', 'cloneArrayBuffer'),
        getItem('cloneBuffer', 'cloneBuffer'),
        getItem('cloneDataView', 'cloneDataView'),
        getItem('cloneRegExp', 'cloneRegExp'),
        getItem('cloneSymbol', 'cloneSymbol'),
        getItem('cloneTypedArray', 'cloneTypedArray'),
        getItem('compareAscending', 'compareAscending'),
        getItem('compareMultiple', 'compareMultiple'),
        getItem('composeArgs', 'composeArgs'),
        getItem('composeArgsRight', 'composeArgsRight'),
        getItem('copyArray', 'copyArray'),
        getItem('copyObject', 'copyObject'),
        getItem('copySymbols', 'copySymbols'),
        getItem('copySymbolsIn', 'copySymbolsIn'),
        getItem('createAssigner', 'createAssigner'),
        getItem('createCaseFirst', 'createCaseFirst'),
        getItem('createMathOperation', 'createMathOperation'),
        getItem('createPadding', 'createPadding'),
        getItem('createRange', 'createRange'),
        getItem('createRound', 'createRound'),
        getItem('createSet', 'createSet'),
        getItem('customDefaultsMerge', 'customDefaultsMerge'),
        getItem('deburrLetter', 'deburrLetter'),
        getItem('equalArrays', 'equalArrays'),
        getItem('equalByTag', 'equalByTag'),
        getItem('equalObjects', 'equalObjects'),
        getItem('freeGlobal', 'freeGlobal'),
        getItem('getAllKeys', 'getAllKeys'),
        getItem('getAllKeysIn', 'getAllKeysIn'),
        getItem('getHolder', 'getHolder'),
        getItem('getMatchData', 'getMatchData'),
        getItem('getSymbols', 'getSymbols'),
        getItem('getSymbolsIn', 'getSymbolsIn'),
        getItem('getTag', 'getTag'),
        getItem('hasUnicode', 'hasUnicode'),
        getItem('initCloneObject', 'initCloneObject'),
        getItem('isFlattenable', 'isFlattenable'),
        getItem('isIndex', 'isIndex'),
        getItem('isIterateeCall', 'isIterateeCall'),
        getItem('isKey', 'isKey'),
        getItem('isPrototype', 'isPrototype'),
        getItem('isStrictComparable', 'isStrictComparable'),
        getItem('iteratorToArray', 'iteratorToArray'),
        getItem('mapToArray', 'mapToArray'),
        getItem('matchesStrictComparable', 'matchesStrictComparable'),
        getItem('memoizeCapped', 'memoizeCapped'),
        getItem('metaMap', 'metaMap'),
        getItem('nodeTypes', 'nodeTypes'),
        getItem('parent', 'parent'),
        getItem('reEscape', 'reEscape'),
        getItem('reEvaluate', 'reEvaluate'),
        getItem('reInterpolate', 'reInterpolate'),
        getItem('root', 'root'),
        getItem('setToArray', 'setToArray'),
        getItem('setToPairs', 'setToPairs'),
        getItem('setToString', 'setToString'),
        getItem('strictIndexOf', 'strictIndexOf'),
        getItem('strictLastIndexOf', 'strictLastIndexOf'),
        getItem('stringSize', 'stringSize'),
        getItem('stringToArray', 'stringToArray'),
        getItem('stringToPath', 'stringToPath'),
        getItem('toKey', 'toKey'),
        getItem('unicodeSize', 'unicodeSize'),
        getItem('unicodeToArray', 'unicodeToArray'),
        getItem('unicodeWords', 'unicodeWords'),
      ]),
      getItem('_.add', 'add'),
      getItem('_.after', 'after'),
      getItem('_.at', 'at'),
      getItem('_.attempt', 'attempt'),
      getItem('_.before', 'before'),
      getItem('_.camelCase', 'camelCase'),
      getItem('_.capitalize', 'capitalize'),
      getItem('_.castArray', 'castArray'),
      getItem('_.ceil', 'ceil'),
      getItem('_.chunk', 'chunk'),
      getItem('_.clamp', 'clamp'),
      getItem('_.clone', 'clone'),
      getItem('_.cloneDeep', 'cloneDeep'),
      getItem('_.cloneDeepWith', 'cloneDeepWith'),
      getItem('_.cloneWith', 'cloneWith'),
      getItem('_.compact', 'compact'),
      getItem('_.cond', 'cond'),
      getItem('_.conforms', 'conforms'),
      getItem('_.conformsTo', 'conformsTo'),
      getItem('_.countBy', 'countBy'),
      getItem('_.create', 'create'),
      getItem('_.debounce', 'debounce'),
      getItem('_.deburr', 'deburr'),
      getItem('_.defaultTo', 'defaultTo'),
      getItem('_.defaultToAny', 'defaultToAny'),
      getItem('_.defaults', 'defaults'),
      getItem('_.defaultsDeep', 'defaultsDeep'),
      getItem('_.defer', 'defer'),
      getItem('_.delay', 'delay'),
      getItem('_.difference', 'difference'),
      getItem('_.differenceBy', 'differenceBy'),
      getItem('_.differenceWith', 'differenceWith'),
      getItem('_.divide', 'divide'),
      getItem('_.drop', 'drop'),
      getItem('_.dropRight', 'dropRight'),
      getItem('_.dropRightWhile', 'dropRightWhile'),
      getItem('_.dropWhile', 'dropWhile'),
      getItem('_.each', 'each'),
      getItem('_.eachRight', 'eachRight'),
      getItem('_.endsWith', 'endsWith'),
      getItem('_.eq', 'eq'),
      getItem('_.eqDeep', 'eqDeep'),
      getItem('_.escape', 'escape'),
      getItem('_.escapeRegExp', 'escapeRegExp'),
      getItem('_.every', 'every'),
      getItem('_.everyValue', 'everyValue'),
      getItem('_.filter', 'filter'),
      getItem('_.filterObject', 'filterObject'),
      getItem('_.findKey', 'findKey'),
      getItem('_.findLast', 'findLast'),
      getItem('_.findLastIndex', 'findLastIndex'),
      getItem('_.findLastKey', 'findLastKey'),
      getItem('_.first', 'first'),
      getItem('_.flatMap', 'flatMap'),
      getItem('_.flatMapDeep', 'flatMapDeep'),
      getItem('_.flatMapDepth', 'flatMapDepth'),
      getItem('_.flatten', 'flatten'),
      getItem('_.flattenDeep', 'flattenDeep'),
      getItem('_.flattenDepth', 'flattenDepth'),
      getItem('_.flip', 'flip'),
      getItem('_.floor', 'floor'),
      getItem('_.flow', 'flow'),
      getItem('_.flowRight', 'flowRight'),
      getItem('_.forEach', 'forEach'),
      getItem('_.forEachRight', 'forEachRight'),
      getItem('_.forOwn', 'forOwn'),
      getItem('_.forOwnRight', 'forOwnRight'),
      getItem('_.fromEntries', 'fromEntries'),
      getItem('_.functions', 'functions'),
      getItem('_.get', 'get'),
      getItem('_.groupBy', 'groupBy'),
      getItem('_.gt', 'gt'),
      getItem('_.gte', 'gte'),
      getItem('_.has', 'has'),
      getItem('_.hasIn', 'hasIn'),
      getItem('_.hasPath', 'hasPath'),
      getItem('_.hasPathIn', 'hasPathIn'),
      getItem('_.head', 'head'),
      getItem('_.inRange', 'inRange'),
      getItem('_.indexOf', 'indexOf'),
      getItem('_.initial', 'initial'),
      getItem('_.intersection', 'intersection'),
      getItem('_.intersectionBy', 'intersectionBy'),
      getItem('_.intersectionWith', 'intersectionWith'),
      getItem('_.invert', 'invert'),
      getItem('_.invertBy', 'invertBy'),
      getItem('_.invoke', 'invoke'),
      getItem('_.invokeMap', 'invokeMap'),
      getItem('_.isArguments', 'isArguments'),
      getItem('_.isArrayBuffer', 'isArrayBuffer'),
      getItem('_.isArrayLike', 'isArrayLike'),
      getItem('_.isArrayLikeObject', 'isArrayLikeObject'),
      getItem('_.isBoolean', 'isBoolean'),
      getItem('_.isBuffer', 'isBuffer'),
      getItem('_.isDate', 'isDate'),
      getItem('_.isElement', 'isElement'),
      getItem('_.isEmpty', 'isEmpty'),
      getItem('_.isEqualWith', 'isEqualWith'),
      getItem('_.isError', 'isError'),
      getItem('_.isFunction', 'isFunction'),
      getItem('_.isLength', 'isLength'),
      getItem('_.isMap', 'isMap'),
      getItem('_.isMatch', 'isMatch'),
      getItem('_.isMatchWith', 'isMatchWith'),
      getItem('_.isNative', 'isNative'),
      getItem('_.isNil', 'isNil'),
      getItem('_.isNull', 'isNull'),
      getItem('_.isNumber', 'isNumber'),
      getItem('_.isObject', 'isObject'),
      getItem('_.isObjectLike', 'isObjectLike'),
      getItem('_.isPlainObject', 'isPlainObject'),
      getItem('_.isRegExp', 'isRegExp'),
      getItem('_.isSet', 'isSet'),
      getItem('_.isString', 'isString'),
      getItem('_.isSymbol', 'isSymbol'),
      getItem('_.isTypedArray', 'isTypedArray'),
      getItem('_.isUndefined', 'isUndefined'),
      getItem('_.isWeakMap', 'isWeakMap'),
      getItem('_.isWeakSet', 'isWeakSet'),
      getItem('_.kebabCase', 'kebabCase'),
      getItem('_.keyBy', 'keyBy'),
      getItem('_.keys', 'keys'),
      getItem('_.keysIn', 'keysIn'),
      getItem('_.last', 'last'),
      getItem('_.lastIndexOf', 'lastIndexOf'),
      getItem('_.lowerCase', 'lowerCase'),
      getItem('_.lowerFirst', 'lowerFirst'),
      getItem('_.lt', 'lt'),
      getItem('_.lte', 'lte'),
      getItem('_.map', 'map'),
      getItem('_.mapKey', 'mapKey'),
      getItem('_.mapObject', 'mapObject'),
      getItem('_.mapValue', 'mapValue'),
      getItem('_.matches', 'matches'),
      getItem('_.matchesProperty', 'matchesProperty'),
      getItem('_.maxBy', 'maxBy'),
      getItem('_.mean', 'mean'),
      getItem('_.meanBy', 'meanBy'),
      getItem('_.memoize', 'memoize'),
      getItem('_.merge', 'merge'),
      getItem('_.mergeWith', 'mergeWith'),
      getItem('_.method', 'method'),
      getItem('_.methodOf', 'methodOf'),
      getItem('_.minBy', 'minBy'),
      getItem('_.multiply', 'multiply'),
      getItem('_.negate', 'negate'),
      getItem('_.nth', 'nth'),
      getItem('_.nthArg', 'nthArg'),
      getItem('_.once', 'once'),
      getItem('_.orderBy', 'orderBy'),
      getItem('_.over', 'over'),
      getItem('_.overArgs', 'overArgs'),
      getItem('_.overEvery', 'overEvery'),
      getItem('_.overSome', 'overSome'),
      getItem('_.pad', 'pad'),
      getItem('_.padEnd', 'padEnd'),
      getItem('_.padStart', 'padStart'),
      getItem('_.parseInt', 'parseInt'),
      getItem('_.partition', 'partition'),
      getItem('_.pick', 'pick'),
      getItem('_.pickBy', 'pickBy'),
      getItem('_.property', 'property'),
      getItem('_.propertyOf', 'propertyOf'),
      getItem('_.pull', 'pull'),
      getItem('_.pullAll', 'pullAll'),
      getItem('_.pullAllBy', 'pullAllBy'),
      getItem('_.pullAllWith', 'pullAllWith'),
      getItem('_.pullAt', 'pullAt'),
      getItem('_.random', 'random'),
      getItem('_.range', 'range'),
      getItem('_.rangeRight', 'rangeRight'),
      getItem('_.reduce', 'reduce'),
      getItem('_.reduceRight', 'reduceRight'),
      getItem('_.reject', 'reject'),
      getItem('_.remove', 'remove'),
      getItem('_.repeat', 'repeat'),
      getItem('_.replace', 'replace'),
      getItem('_.result', 'result'),
      getItem('_.round', 'round'),
      getItem('_.sample', 'sample'),
      getItem('_.sampleSize', 'sampleSize'),
      getItem('_.set', 'set'),
      getItem('_.setWith', 'setWith'),
      getItem('_.shuffle', 'shuffle'),
      getItem('_.size', 'size'),
      getItem('_.slice', 'slice'),
      getItem('_.snakeCase', 'snakeCase'),
      getItem('_.some', 'some'),
      getItem('_.someValue', 'someValue'),
      getItem('_.sortedIndex', 'sortedIndex'),
      getItem('_.sortedIndexBy', 'sortedIndexBy'),
      getItem('_.sortedIndexOf', 'sortedIndexOf'),
      getItem('_.sortedLastIndex', 'sortedLastIndex'),
      getItem('_.sortedLastIndexBy', 'sortedLastIndexBy'),
      getItem('_.sortedLastIndexOf', 'sortedLastIndexOf'),
      getItem('_.sortedUniq', 'sortedUniq'),
      getItem('_.sortedUniqBy', 'sortedUniqBy'),
      getItem('_.split', 'split'),
      getItem('_.startCase', 'startCase'),
      getItem('_.startsWith', 'startsWith'),
      getItem('_.subtract', 'subtract'),
      getItem('_.sum', 'sum'),
      getItem('_.sumBy', 'sumBy'),
      getItem('_.tail', 'tail'),
      getItem('_.take', 'take'),
      getItem('_.takeRight', 'takeRight'),
      getItem('_.takeRightWhile', 'takeRightWhile'),
      getItem('_.takeWhile', 'takeWhile'),
      getItem('_.test', 'test'),
      getItem('_.throttle', 'throttle'),
      getItem('_.times', 'times'),
      getItem('_.toArray', 'toArray'),
      getItem('_.toFinite', 'toFinite'),
      getItem('_.toInteger', 'toInteger'),
      getItem('_.toLength', 'toLength'),
      getItem('_.toNumber', 'toNumber'),
      getItem('_.toPath', 'toPath'),
      getItem('_.toPlainObject', 'toPlainObject'),
      getItem('_.toSafeInteger', 'toSafeInteger'),
      getItem('_.toString', 'toString'),
      getItem('_.transform', 'transform'),
      getItem('_.trim', 'trim'),
      getItem('_.trimEnd', 'trimEnd'),
      getItem('_.trimStart', 'trimStart'),
      getItem('_.truncate', 'truncate'),
      getItem('_.unescape', 'unescape'),
      getItem('_.union', 'union'),
      getItem('_.unionBy', 'unionBy'),
      getItem('_.unionWith', 'unionWith'),
      getItem('_.uniq', 'uniq'),
      getItem('_.uniqBy', 'uniqBy'),
      getItem('_.uniqWith', 'uniqWith'),
      getItem('_.uniqueId', 'uniqueId'),
      getItem('_.unset', 'unset'),
      getItem('_.unzip', 'unzip'),
      getItem('_.unzipWith', 'unzipWith'),
      getItem('_.update', 'update'),
      getItem('_.updateWith', 'updateWith'),
      getItem('_.upperCase', 'upperCase'),
      getItem('_.upperFirst', 'upperFirst'),
      getItem('_.values', 'values'),
      getItem('_.without', 'without'),
      getItem('_.words', 'words'),
      getItem('_.xor', 'xor'),
      getItem('_.xorBy', 'xorBy'),
      getItem('_.xorWith', 'xorWith'),
      getItem('_.zip', 'zip'),
      getItem('_.zipObject', 'zipObject'),
      getItem('_.zipObjectDeep', 'zipObjectDeep'),
      getItem('_.zipWith', 'zipWith'),
    ]),
  ]),
  getItem('其它内容', 'others', <AppstoreAddOutlined />, [
    getItem('腾讯云（待完成）', 'tengxunyun', <TencentCloudIcon />),
    getItem(
      '阿里云（待完成）',
      'aliyun',
      <AliyunOutlined style={{ color: '#ED732E' }} />
    ),
    getItem('CodeSandbox（待完成）', 'codesandbox', <CodeSandboxOutlined />),
    getItem('PS Online（待完成）', 'ps_onine', <BgColorsOutlined />),
    getItem('MDN（待完成）', 'mdn', <MozillaIcon />),
    getItem('墨刀（待完成）', 'modao', <ModaoIcon />),
    getItem('Figma（待完成）', 'figma', <FigmaIcon />),
    getItem('Jenkins（待完成）', 'jenkins', <JenkinsIcon />),
    getItem('CentOS（待完成）', 'centos', <CentosIcon />),
    getItem('Nginx（待完成）', 'nginx', <NginxIcon />),
    getItem('Vue（待完成）', 'vue', <VueIcon />),
    getItem('Nodejs（待完成）', 'nodejs', <NodejsIcon />),
    getItem('SSL（待完成）', 'ssl', <SSLIcon />),
    getItem('TypeScript（待完成）', 'typescript', <TypeScriptIcon />),
    getItem('SASS（待完成）', 'sass', <SASSIcon />),
    getItem('滴答清单（待完成）', 'didalist', <ListIcon />),
    getItem('VSCode（待完成）', 'vscode', <VsCodeIcon />),
  ]),
];

const SideBar = () => {
  const navigate = useNavigate();

  const onClick = (e: any) => {
    const path = e.keyPath
      .reverse()
      .map((i: string) => `/${i}`)
      .join('');

    navigate(path);
  };
  return (
    <div className="sidebar">
      <Menu
        className="menu"
        onClick={onClick}
        defaultSelectedKeys={['components']}
        defaultOpenKeys={['components']}
        mode="inline"
        theme="dark"
        items={items}
      />
    </div>
  );
};

export default SideBar;
